### ISSUE TITLE
Return is out of place

### ISSUE THREAD

**Issue by mmphego** [udacity/CNAND_nd064_C4_Observability_Starter_Files#10]
Not sure if this is by design or a copy and paste gone wrong

https://github.com/udacity/CNAND_nd064_C4_Observability_Starter_Files/blob/e812528661f519722e9fdfd73a9f9121409931ad/Project_Starter_Files-Building_a_Metrics_Dashboard/reference-app/trial/app.py#L57

**Comment by supirman** [comment]
I think it is just a quick hack since the API endpoint below no longer works 

https://jobs.github.com/positions.json?description=python
