### ISSUE TITLE
Pin k3s version to v1.19.5+k3s1

### ISSUE THREAD

**Issue by ericcgu** [udacity/CNAND_nd064_C4_Observability_Starter_Files#16]
Theres a IP Table bug in OpenSUSE that can be resolved by pinning k3s version.

https://github.com/k3s-io/k3s/releases/tag/v1.19.5+k3s1

https://knowledge.udacity.com/questions/500205

**Comment by ericcgu** [comment]
https://github.com/udacity/CNAND_nd064_C4_Observability_Starter_Files/pull/17

**Comment by TheJaySmith** [comment]
#17  has been merged. Than you so much!
