### ISSUE TITLE
Instructions for the project : step 3 - deploying the application

### ISSUE THREAD

**Issue by mmphego** [udacity/CNAND_nd064_C4_Observability_Starter_Files#21]
Hi, @TheJaySmith cc: @SudKul 

See the [knowledge question](https://knowledge.udacity.com/questions/745335) below, I have submitted multiple *Mentor Content Escalation* forms wrt to the inconsistencies in this project and lesson. As a mentor, I am in the firing line!

![image](https://user-images.githubusercontent.com/7910856/142148560-90656074-c868-4909-a285-0e2fe6823e13.png)
![image](https://user-images.githubusercontent.com/7910856/142148600-50a01ccf-6685-4934-8f3d-f9a49a133724.png)

**Comment by TheJaySmith** [comment]
<img width="867" alt="udacity-screen-1" src="https://user-images.githubusercontent.com/7904755/142529353-cc8d859f-7b02-4860-b827-4e0e20c0a779.png">

This has been updated. Can you confirm?

**Comment by mmphego** [comment]
Can't confirm as I am unable to change to latest version.
![image](https://user-images.githubusercontent.com/7910856/142582013-db9a36d4-0d52-44bc-898c-311341534111.png)

https://classroom.udacity.com/nanodegrees/nd064/parts/cd0310/modules/f0d276cb-e5ae-4cf0-89fa-bc69c0c38d9a/lessons/889da23a-d0eb-4cbb-8f53-2a10ec57ff21/concepts/e70c0141-d1aa-4c71-ad63-1e63afd44930

![image](https://user-images.githubusercontent.com/7910856/142581863-b6cf7499-12fd-4349-9872-7cf0f9d93547.png)

**Comment by TheJaySmith** [comment]
I think it should be alright to close it as it appears updated now.

**Comment by SudKul** [comment]
Thanks, @TheJaySmith 
@mmphego all learners will see the updated step, as pointed out by Jay in the previous comment. 
We have verified today.
