### ISSUE TITLE
The box you're attempting to add has no available version that matches the constraints you requested.

### ISSUE THREAD

**Issue by mmphego** [udacity/CNAND_nd064_C4_Observability_Starter_Files#4]
Issue regarding OpenSuse image version constraint.

![image](https://user-images.githubusercontent.com/7910856/104658947-76b7b480-56cc-11eb-9ed6-9dbf6798aae3.png)

**System Info**
![image](https://user-images.githubusercontent.com/7910856/104659194-e0d05980-56cc-11eb-972d-f70f9986a5f2.png)

**Comment by SudKul** [comment]
Thanks @mmphego for reporting the issue. 
We have bumped up the box version in the Exercise_Starter_Files/Vagrantfile file. 
See the changes here: https://github.com/udacity/CNAND_nd064_C4_Observability_Starter_Files/pull/11/files

You can use any compatible version between `15.2.31.300` and `15.2.31.500`
