### ISSUE TITLE
Failed to download "prometheus-community/kube-prometheus-stack" at version "0.7"

### ISSUE THREAD

**Issue by mmphego** [udacity/CNAND_nd064_C4_Observability_Starter_Files#6]
Not sure if this is related to the content under this repo, but it's related to the lessons or project setup

Please note that `version 0.7` of `"prometheus-community/kube-prometheus-stack"` is not available.

![image](https://user-images.githubusercontent.com/7910856/105035347-82580200-5a63-11eb-8888-8b738b453e16.png)

The only available versions of "prometheus-community/kube-prometheus-stack" are as follows
`helm search repo prometheus -l | grep "prometheus-community/kube-prometheus-stack"`
![image](https://user-images.githubusercontent.com/7910856/105035501-c0edbc80-5a63-11eb-9c37-aaa21fdd4cf2.png)

**Comment by TheJaySmith** [comment]
Is this in regards to a specific file or is this within the Udacity UI?

**Comment by AbeFeinberg** [comment]
@mmphego Thanks again for raising these – Jay is making fixes and could use some clarification on what you saw here, if you can provide additional context.

**Comment by AbeFeinberg** [comment]
@TheJaySmith I think this may refer to Step 2: Setting up Observability in the classroom project instructions. Maybe it is having the student install version 0.7 in the instructions there? Can you check?

**Comment by mmphego** [comment]
I think this has since been resolved.
![image](https://user-images.githubusercontent.com/7910856/141604075-2617ee59-a1db-403a-9d84-b5847ade5d3b.png)
