### ISSUE TITLE
/reference-app/trial/app.py: No module named 'prometheus_client'

### ISSUE THREAD

**Issue by mmphego** [udacity/CNAND_nd064_C4_Observability_Starter_Files#7]
Ran: `kubectl apply -Rf manifests/app/`

Status of pods: `CrashLoopBackOff`
![image](https://user-images.githubusercontent.com/7910856/105153028-9dcd1680-5b10-11eb-92df-e3664364647b.png)

Due to missing dependency/
![image](https://user-images.githubusercontent.com/7910856/105150767-d7e8e900-5b0d-11eb-82c3-cc116a895bd4.png)

Then, I tried running the `app.py` inside the container.
![image](https://user-images.githubusercontent.com/7910856/105152822-59da1180-5b10-11eb-9128-5c4399421190.png)

The verified if `prometheus` submodule is available on `jaeger_client==4.3.0`, which isn't
![image](https://user-images.githubusercontent.com/7910856/105153461-2350c680-5b11-11eb-9335-2328b14f5b9f.png)

## The Fix

Add `prometheus_client==0.9.0` into the `requirements.txt`
![image](https://user-images.githubusercontent.com/7910856/105153715-6a3ebc00-5b11-11eb-9fae-41282996bb14.png)

**Comment by TheJaySmith** [comment]
Fixed via https://github.com/udacity/CNAND_nd064_C4_Observability_Starter_Files/commit/eab299413652a5137fa756c4be4a743574712376
