### ISSUE TITLE
Undefined imports: /reference-app/

### ISSUE THREAD

**Issue by mmphego** [udacity/CNAND_nd064_C4_Observability_Starter_Files#8]
Issues with deploying `trial` due to undefined imports.

![image](https://user-images.githubusercontent.com/7910856/105159761-1daaaf00-5b18-11eb-9d0a-d776c3da5ff6.png)

Running `flake8` revealed.

![image](https://user-images.githubusercontent.com/7910856/105159370-aecd5600-5b17-11eb-8b6b-f8207fbc05b0.png)

**Comment by SudKul** [comment]
@mmphego 
We have recently updated the course exercises. 
Is the issues mentioned above still unresolved? If yes, please point me to the erroneous code/file. 
Thank you.
