### ISSUE TITLE
trial: jinja2.exceptions.TemplateNotFound: main.html

### ISSUE THREAD

**Issue by mmphego** [udacity/CNAND_nd064_C4_Observability_Starter_Files#9]
`curl`-ing `localhost:30048` issues `500 Internal Server Error` due an exception on `trial/app.py`, missing the `main.html` template.
![image](https://user-images.githubusercontent.com/7910856/105166665-58b0e080-5b20-11eb-9407-527bb5f25d0c.png)

Running pods
![image](https://user-images.githubusercontent.com/7910856/105166475-27d0ab80-5b20-11eb-9a2f-50faed37ff33.png)

Error encountered
![image](https://user-images.githubusercontent.com/7910856/105166343-096ab000-5b20-11eb-859a-86c8f630edf3.png)

**Comment by SudKul** [comment]
Hi @mmphego 
You cannot communicate from the node machine (Vagrant VM,  in this case) to Kubernetes pods using the `localhost:XXXX`.  There are  pods within each cluster, and every pod gets its own IP address (different from the cluster IP). 
Refer to https://kubernetes.io/docs/concepts/cluster-administration/networking/ for more details.  However, the Kubernetes Cluster Networking is not the focus of the current exercise in question above. 

Should you have more questions, feel free to ask mentors on the suitable platform - https://knowledge.udacity.com/

Happy learning.
